DROP USER c##hr CASCADE;
CREATE USER c##hr IDENTIFIED BY hr DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp PROFILE DEFAULT;
GRANT CONNECT, RESOURCE TO c##hr;
GRANT CREATE VIEW, CREATE SYNONYM TO c##hr;
GRANT UNLIMITED TABLESPACE TO c##hr;
ALTER USER c##hr ACCOUNT UNLOCK;